### ISSUE TITLE
Compatibility with other HVS switchers.

### ISSUE THREAD

**Issue by Fader-Monkey** [bitfocus/companion-module-fora-hvs#1]
I started doing some testing with two switchers. So far all is working on my HVS 100. I have a different software version than what you tested with and I will leave screenshots of version info. I had to restart my switcher before it connected the first time but after that I have had no issues to report on the HVS 100. I will keep testing.

I have not been able to get this module to work at all with my HVS 2000. I know this module is built for a HVS 100, but the original module request was for all of the HVS switchers. I suspect that the web-socket approach would have to be rewritten for the 2000 series switcher. At least I know the web GUI for the 2000 is very different from the 100. 

here are the software/firmware versions of the switchers I am testing on.

HVS 100
<img width="414" alt="HVS 100 Version" src="https://user-images.githubusercontent.com/47360319/75702686-862c3b80-5c7b-11ea-8bbf-a0783cfedeb6.png">

HVS 2000
<img width="452" alt="Screen Shot 2020-03-02 at 1 36 39 PM" src="https://user-images.githubusercontent.com/47360319/75710860-f2fb0200-5c8a-11ea-86af-37f536dbd6f0.png">
<img width="734" alt="Screen Shot 2020-03-02 at 1 36 21 PM" src="https://user-images.githubusercontent.com/47360319/75710861-f3939880-5c8a-11ea-8039-116380910ff1.png">

**Comment by MichaelAllen** [comment]
Thanks for helping to test the module. Glad to hear the 100 is working for you. 

For the 2000, let's try to get a network log to see if the protocol is at least similar, or if it will need an entirely different module. Here is the process if you are using Chrome:
1. Go to the switcher's web interface and open the Bus/Trans page, or whatever the equivalent page is on the 2000.
1. Open the web inspector's (ctrl+shift+I) network tab and refresh the page.
1. Change a few things to get some data. (pgm source, cut transition, keyer, etc.)
1. Right-click on any line in the inspector and select "Save all as HAR with content".
1. Upload that file here so I can take a look at how the web interface is talking to the switcher.

**Comment by Fader-Monkey** [comment]
Here is the info I got on the HVS 2000 web page. all of the info is from the web panel page let me know if you want info from the event recall pages and such.
also there is a password page before you get to the web panel.


![Screen Shot 2020-03-02 at 6 41 30 PM](https://user-images.githubusercontent.com/47360319/75732023-ec827f80-5cb6-11ea-839e-ed1810d97c2e.png)

[10.31.18.32.har.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4278720/10.31.18.32.har.zip)

**Comment by MichaelAllen** [comment]
The good news is that it looks like basically the same protocol as the 100. I was able to pull the same javascript files from your archive that I based most of the code for the 100 on, so it may just be a matter of mapping those commands in the plugin.

I didn't see any authentication recorded in the network log, so I'm thinking the password is only for the web interface, and not for the underlying control socket connection.

Were you able to get the plugin to connect to the 2000 (green OK status in companion) just no commands worked, or would it not connect (red error status)?

**Comment by Fader-Monkey** [comment]
here is the error I get when I use any of the commands.

<img width="406" alt="Screen Shot 2020-03-05 at 4 26 41 PM" src="https://user-images.githubusercontent.com/47360319/76032025-91db6480-5efe-11ea-93c9-0a80d2d800b5.png">


I get a red Error message after using the buttons, but it stays white until I press a button.

<img width="741" alt="Screen Shot 2020-03-05 at 4 27 23 PM" src="https://user-images.githubusercontent.com/47360319/76032071-b20b2380-5efe-11ea-86ce-162154323f14.png">

**Comment by MichaelAllen** [comment]
With the most recent version of the module (v1.0.3) I added some better logging if something goes wrong. If you are running from source, you can update by`cd` into the module's folder, and running `git pull`, followed by `git checkout master`. That should get you the latest version.

2 things to note:
- I changed the name of the module from `fora-hvs100` to `fora-hvs` in v1.0.2 so you will need to delete the instances you have created in companion and re-add it.
- Most of the logging will come out in the terminal. So you will want to make sure to copy the output from the terminal when the problem happens. An easy way to do that is to launch companion with this command: `yarn dev 2>&1 | tee -a ~/Desktop/companion.log` That will save everything that companion writes to the terminal into a file on your desktop called `companion.log`

**Comment by Fader-Monkey** [comment]
do you need me to continue testing this for HVS 2000? Is there anything in that update that would make it work?
I added the module into my weekly use but then the whole Covid-19 happened and my weekly workflow did not happen.

**Comment by MichaelAllen** [comment]
I don't think any of the changes I've made will have fixed the 2000 not connecting, but I did add better logging for errors now so I should hopefully be able to pinpoint the problem if you can try to connect then post the debug logging from the terminal. (see my above comment for an easy way to dump the log to a file)

**Comment by Fader-Monkey** [comment]
so I had to reinstall everything because my laptop died. but I just ran some commands to my HVS 2000 and here is the log file.
[companion.log.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4452275/companion.log.zip)

**Comment by MichaelAllen** [comment]
Based on that log file, it looks like you aren't getting a connection error anymore. Just nothing happens when you press the buttons. Is that correct?

If so, can you try a few commands in the custom command action to make sure the communication is good? `SET.M1BG_XPT_PST:1` should PREVIEW source 1 on ME1, `SET.M1BG_TRANSITION:CUT` should preform a cut transition on ME1, and `SET.M1K1_TRANSITION:AUTO` I think should toggle ME1 Key1.

**Comment by Fader-Monkey** [comment]
Im actually thinking it has more to do with my VPN connection. other modules that did not have problems before are now having issues. let me try retesting with a local machine.

**Comment by Fader-Monkey** [comment]
Edit: didn't read the comment right. all custom commands are working as expected.

ok so the  SET.M1BG_XPT_PST:1.    &.   SET.M1BG_TRANSITION:CUT,  &.  SET.M1K1_TRANSITION:AUTO 
commands work when using the custom command feature. here is the log.


[companion HVS 2000 V2.log.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4570913/companion.HVS.2000.V2.log.zip)

Thanks! sorry this took forever. My workflow looks so different now.

**Comment by MichaelAllen** [comment]
Awesome, so the communication with the switcher is good now. That was the hard part, now I just need to implement a "Select your model" option in the instance screen so the module knows what version of the commands to send.

**Comment by Fader-Monkey** [comment]
anything else you need from me on this? any more capture on network logs for other commands? thanks again for making this possible.

**Comment by Fader-Monkey** [comment]
here are the js files off the web page for the HVS 2000. Hopefully this can help to create the websocket commands and figure out feedback for this module. 
[HVS 2000 js.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4841520/HVS.2000.js.zip)


also here are some know working commands tested on my HVS 2000

SET.FLX1_TRANSITION:AUTO
(flex key 1 auto)

SET.M1BG_XPT_PST:1
(me1 preview input 1)

SET.M1BG_XPT_PGM:1
(me1 program input 1)

SET.MEL1BG_XPT_PST:1
(MElite1 preview input 1)

SET.MEL1BG_XPT_PGM:1
(MElite1 program 1)

SET.M1BG_TRANSITION:CUT
(ME1 cut BKG Operation)

SET.M1K1_TRANSITION:AUTO
(ME1 Key 1 auto trans operation)

**Comment by Frazerchurch** [comment]
I have an HVS-2000, how do I get companion to work with it? I don't even see For.A listed on the manufacturers  in the admin panel

**Comment by MichaelAllen** [comment]
@Fader-Monkey thanks for posting those files. I have been away for a bit, but I'll starting working on HVS 2000 support this week. I can't give a solid ETA because it will basically be a complete rewrite of the module since the 100 and 2000 don't share any of the same commands. 

Thanks for your help with this so far. I'll ping you when I have something ready to test.

**Comment by MichaelAllen** [comment]
@Frazerchurch The ForA module is only available in Companion v2. If you are on v1.4 you will want to upgrade as v2 contains several bug fixes and a lot of new modules. Although v2 is technically still in beta, we have been running it for several months with no issues. 

Also, note that this module currently only works with the HVS 100 and 110. I have recently started working on support for the 2000, but don't have an ETA for finishing it.

**Comment by Fader-Monkey** [comment]
@MichaelAllen no problem dude, thanks for working on this I know you have to do this on your own time. im just glad to help, thats why all this stuff is open source. we are all just trying to make each-others lives easier. I already use the custom commands in our workflow and it has made my volunteers so happy.

**Comment by MichaelAllen** [comment]
@Fader-Monkey I am close to having something ready to test. I just need some more information on the available inputs. 
Can you capture a network log of the settings page where you name the inputs? (Same process we used [here](https://github.com/bitfocus/companion-module-fora-hvs/issues/1#issuecomment-593617524) to get the network log)

Also, if you have the manual for the HVS2000 in a format you could upload, that would be awesome. My google-fu is failing me for some reason; I can't find a copy online.

**Comment by Fader-Monkey** [comment]
I don't think there is a page for that on the 2000. I know the page you are talking about on the 100. 

if you use the custom command: GET.SIGNALS_INFO

it will return long and short names for all inputs. here is the log of what it returns.

[companion GET.SIGNALS_INFO.log.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4874091/companion.GET.SIGNALS_INFO.log.zip)

here are the other info commands from what i can tell. 
<img width="298" alt="Screen Shot 2020-07-04 at 5 40 00 PM" src="https://user-images.githubusercontent.com/47360319/86522018-77b68200-be1d-11ea-90a9-2a69e5d7b4a8.png">

also there seems to be a response for each time a XPT is set, maybe this could be used for tally. it looks like this: 
<img width="230" alt="Screen Shot 2020-07-04 at 5 36 48 PM" src="https://user-images.githubusercontent.com/47360319/86522039-c237fe80-be1d-11ea-9306-60285c837c6a.png">

**Comment by MichaelAllen** [comment]
@Fader-Monkey I have something ready to test when you have a chance. It is over on [this branch](https://github.com/MichaelAllen/companion-module-fora-hvs/tree/feature-ma-hvs2000) because I didn't want to merge it into master until I am sure that it actually works.

Here is how to get your dev environment to use this fork:
1) `cd` to your companion clone
1) `yarn update`
1) `cd lib/module/fora-hvs`
1) `git remote add michaelallen https://github.com/MichaelAllen/companion-module-fora-hvs.git`
1) `get fetch michaelallen`
1) `git checkout michaelallen/feature-ma-hvs2000`
1) `cd ../../..`
1) `yarn run dev`

If you would prefer me to build a `.app` file instead, let me know and I can send that over.

**Comment by Fader-Monkey** [comment]
some quick testing seems to show that it is working as it should. I will do some more testing once Im in the same room as the switcher, and upload logs. 
quickly tested: PVW/PGM set XPT Me 1/MeLite1          also tested reconnect command  and transition commands for me1/MeLite1

I still need to test: switching auxes/reboot/recall event.


nice to haves would be dropdowns for keys and flex keys with commands:
`SET.FLX1_TRANSITION:AUTO`
`SET.FLX1_TRANSITION:CUT`
`SET.M1K1_TRANSITION:AUTO`
`SET.M1K1_TRANSITION:CUT`

for keys 1-4 on me1/ 1-4 on me2 / 1-4 flexkeys

**Comment by MichaelAllen** [comment]
I added key & flex-key transition actions for the 100 and the 2000. You should be able to pull the changes with a `git pull --rebase` in the `companion/lib/module/fora-hvs` folder.

**Comment by MichaelAllen** [comment]
I didn't see any control commands for events in the 2000's source files. There are commands for store/recall/delete scene, though. I'm thinking is probably the same thing just with a different name.

Try this custom command to see if it works to recall event/scene 5: `CMD.02010205`. If so, I can add it to the protocol file.
If that doesn't work, can you capture what the switcher is sending when you click to recall an event/scene in the web GUI?

**Comment by Fader-Monkey** [comment]
key and flex keys are working great! I will have to look at the events on the 7th. honestly don't know what events the tech director has programed and don't just want to start recalling events without knowing what I'm looking for.

**Comment by Fader-Monkey** [comment]
ok here are network logs of event recalls. 
there are different types of events. global and local. 
the part after "event id"= is the recall scope. using the "GET.EVENT" will return the stored recall scope

here are the logs for global events.
[10.30.0.42 events global.har.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4881270/10.30.0.42.events.global.har.zip)

here are logs for local events (specifically ME2)
[10.30.0.42 events local me2.har.zip](https://github.com/bitfocus/companion-module-fora-hvs/files/4881284/10.30.0.42.events.local.me2.har.zip)

example code looks like:
 send `GET.ME2_EVENT_FLAG:4` (select event)
receive. `SET.ME2_EVENT_FLAG:4=0000 0FFF 0000 0000 0000 0000 0000 0000 0000 0C00 0000 0000 0000 0000 00F0 0000 0000`

send `SET.ME2_RECALL:4=0 0000 0FFF 0000 0000 0000 0000 0000 0000 0000 0C00 0000 0000 0000 0000 00F0 0000 0000` (recall event)
Receive `SET.ME2_EVENT_LASTRECALL_NO:4`


or for global:
send `GET.EVENT_FLAG:5`
receive `SET.EVENT_FLAG:5=0FFF 0FFF 0000 0000 0000 0000 0000 0000 0000 0F00 0000 0000 0000 0000 00FF 0000 0000`

send `SET.RECALL:5=0 0FFF 0FFF 0000 0000 0000 0000 0000 0000 0000 0F00 0000 0000 0000 0000 00FF 0000 0000`
receive `SET.EVENT_LASTRECALL_NO:5`

**Comment by Fader-Monkey** [comment]
just tested AUX and Reboot.

aux works great no problems there.

reboot- disconnects and reconnects to websocket but does not reboot MU. I cant find the option to reboot the MU from the web page on the HVS 2000. maybe they left it out. it is on the GUI windows program that comes with the 2000 just not the web page.

**Comment by Fader-Monkey** [comment]
can the Aux sources be added to the available sources on the set ME and Set MeLite drop downs? (sources=72-107)
ie allow the ME2 PGM to be taken as a source in ME1 
or take ME2 PGM as a source into MeLite.

**Comment by MichaelAllen** [comment]
> can the Aux sources be added to the available sources on the set ME and Set MeLite drop downs? (sources=72-107)
> ie allow the ME2 PGM to be taken as a source in ME1 
> or take ME2 PGM as a source into MeLite.

Sure thing, that will be an easy change. 

Are there any AUX-only sources, or would it just be the same source list for all of those actions?

**Comment by Fader-Monkey** [comment]
its the same source list. although it does look like the list goes all the way to 178 on closer look. that might be a long list. just depends on what people need access to. 
72-107 are ME outs
108-123 are clean outs
124-127 are effects
130-137 are color corrections (cant think of why that would need to be a source)
141-156  are auxs. (redundant)
157-165 are MeLites (ones that are not assigned don't even show up)i ie in my setup there is no 160,161,162
169-174 are still store keys
175-178 are multiview outs.

main ones I can actually think of being useful are Me outs (72-107) and MeLite (157-165)

**Comment by MichaelAllen** [comment]
Support for the HVS 2000 is now available in the latest Companion v2.0 beta builds. 

Thank you for your help getting this working. 
I'm going to go ahead and close this thread since the original issue is solved. I split your notes about event recall off into a new thread since that is not implemented yet.
