### ISSUE TITLE
For-a HVS series switchers

### ISSUE THREAD

**Issue by Fader-Monkey** [bitfocus/companion-module-fora-hvs#3]
I would like to request a module for the For-A HVS series of switchers.I can help test if needed I have both a HVS 100 and a HVS 2000. I reached out to For-A a few months back and they said that a companion module is on their list but not at the top of their list. I will include all info I got from For-A here:

Creating a library for Companion software is on our list of things to do but hasn’t reached the top yet.
 
Here are the control codes for the HVS switchers.
The implementation only various by the number of ME and Aux busses.
The protocol is based on the SONY DVS editor protocol.
You will need to enable the editor function on your switchers. It is in the Ext Interface menu.

[DVS_Combined_Protocol.pdf](https://github.com/bitfocus/companion-module-requests/files/4042221/DVS_Combined_Protocol.pdf)

**Comment by MichaelAllen** [comment]
Support for the HVS 2000 is now available in the latest Companion v2.0 beta builds.
